baseurl = "https://www.marion-immo.lu/"           # The base URL of your Hugo site
author = "Marion Boudier"   # The author name
googleAnalytics = ""    # Your Google Analytics tracking ID
enableRobotsTXT = true
language = "fr-FR"
paginate = 3            # The numbers of posts per page
theme = "terrassa"      # Your Hugo theme
DefaultContentLanguage = "fr"
summaryLength = 20

[languages]
  [languages.fr]
    title = "Marion Boudier Immobilier"     # The title of your Hugo site
    weight = 1
    languageName = 'Français'
    [languages.fr.params]
        description = "Welcome on Marion Boudier website, your real estate agent in Luxembourg"
        favicon = "favicon.ico"
        logo = "images/logo-fond-noir.png"
  [languages.en]
    title = "Marion Boudier Immobilier"
    weight = 2
    languageName = 'English'
    [languages.en.params]
        description = "Welcome on Marion Boudier website, your real estate agent in Luxembourg"
        favicon = "favicon.ico"
        logo = "images/logo-fond-noir.png"

[params]
    description = "Bienvenu sur le site de Marion Boudier, votre agent immobilier au Luxembourg"
    favicon = "favicon.ico"
    logo = "images/logo-fond-noir.png"

[params.hero]
    textColor = "blue" # Empty for default color

[params.contact]
    email = "marion.boudier@marion-immo.lu"
    phone = "+352 661 51 06 51"
    skype = ""
    address = ""


 [params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"   

[params.form] # Contact form
    netlify = false
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Votre nom"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Votre email"
    inputMsgName = "message"
    inputMsgLabel = "Décrivez votre bien ou précisez votre demande"
    inputMsgLength = 750
    inputSubmitValue = "Demander une évaluation gratuite"    

[markup.goldmark.renderer]
unsafe= true